name: Build_immwrt1200ac

on: 
  release:
    types: [published]

  #push:
  #  branches: 
  #    - master

  schedule:
    - cron: 0 19 * * *

  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        ref: master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        docker rmi `docker images -q`
        sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php
        sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
        sudo -E apt-get update
        curl -s https://build-scripts.immortalwrt.eu.org/init_build_environment.sh | sudo bash
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
        df -h
          
    - name: Clone source code
      env: 
        REPO_URL: git://github.com/immortalwrt/immortalwrt
        REPO_BRANCH: master
      run: git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt

    - name: Update & Install feeds
      working-directory: ./openwrt
      run: |
        perl -pi -e 's/https/git/' ./feeds.conf.default
        ./scripts/feeds update -a
        ./scripts/feeds install -a
    - name: Configuration Customization - Build_immwrt1200ac
      run: |
        cp -f immwrt1200ac.config openwrt/.config
        chmod +x ./customize_wrt1200ac.sh && ./customize_wrt1200ac.sh
        cd openwrt && make defconfig
        
    - name: Download package
      working-directory: ./openwrt
      run: |
        make download -j8
        find dl -size -1024c -exec rm -f {} \;

    - name: Build firmware
      working-directory: ./openwrt
      run: |
        echo -e "$(nproc) thread build."
        # make -j$(nproc) V=s
        make -j$(nproc)
        echo "======================="
        echo "Space usage:"
        echo "======================="
        df -h
        echo "======================="
        du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
        du -h --max-depth=1 ./build_dir
        du -h --max-depth=1 ./bin

    - name: Assemble artifact
      working-directory: ./openwrt
      run: |
        rm -rf ./artifact/
        mkdir -p ./artifact/
        # find ./bin/targets/ -name "*combined*img*" | xargs -i mv -f {} ./artifact/
        # find ./bin/targets/ -name "*factory*img*" | xargs -i mv -f {} ./artifact/
        find ./bin/targets/ -name "*sysupgrade*bin*" | xargs -i mv -f {} ./artifact/
          
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: OpenWrt
        path: ./openwrt/artifact/
